spring:
  application:
    name: smartdelivery
  datasource:
    url: jdbc:postgresql://localhost:5432/smartdelivery
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update